{{- if .Values.operator.enabled }}
{{- if .Values.operator.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator.namespace }}
  labels:
    {{- include "catalyst.operator.labels" . | nindent 4 }}
{{- end }}
{{- end }}
