{{- if .Values.operator.enabled }}
{{- if .Values.operator.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "catalyst.fullname" . }}-operator-manager-rolebinding
  labels:
    {{- include "catalyst.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "catalyst.fullname" . }}-operator-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "catalyst.operator.serviceAccountName" . }}
  namespace: {{ .Values.operator.namespace }}
{{- end }}
{{- end }}
