{{- if .Values.operator.enabled }}
{{- if .Values.operator.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalyst.fullname" . }}-operator-metrics
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "catalyst.operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.operator.metrics.service.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "catalyst.operator.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
