{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catalyst.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalyst.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
{{- end }}
