{{- if .Values.web.enabled }}
{{- if .Values.web.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalyst.fullname" . }}-web
  labels:
    {{- include "catalyst.web.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.web.env.DATABASE_URL | quote }}
  NEXTAUTH_URL: {{ .Values.web.env.NEXTAUTH_URL | quote }}
  NEXTAUTH_SECRET: {{ .Values.web.env.NEXTAUTH_SECRET | quote }}
  {{- if .Values.web.env.GITHUB_CLIENT_ID }}
  GITHUB_CLIENT_ID: {{ .Values.web.env.GITHUB_CLIENT_ID | quote }}
  {{- end }}
  {{- if .Values.web.env.GITHUB_CLIENT_SECRET }}
  GITHUB_CLIENT_SECRET: {{ .Values.web.env.GITHUB_CLIENT_SECRET | quote }}
  {{- end }}
  {{- if .Values.web.env.GITHUB_PAT }}
  GITHUB_PAT: {{ .Values.web.env.GITHUB_PAT | quote }}
  {{- end }}
{{- end }}
{{- end }}
