{{- if .Values.web.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catalyst.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalyst.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
