{{- if .Values.postgresql.enabled }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (required "postgresql.auth.existingSecret is required" .Values.postgresql.auth.existingSecret)).data | default dict }}
{{- $postgresqlPasswordB64 := (index $secret "password") | default (randAlphaNum 16 | b64enc) }}
{{- $postgresqlAdminPasswordB64 := (index $secret "postgres-password") | default (randAlphaNum 16 | b64enc) }}
{{- $postgresqlPassword := $postgresqlPasswordB64 | b64dec }}
{{- $postgresqlAdminPassword := $postgresqlAdminPasswordB64 | b64dec }}
{{- $host := printf "%s.%s.svc.cluster.local" (printf "%s-%s" .Release.Name "postgresql") .Release.Namespace }}
{{- $port := "5432" }}
{{- $username := .Values.postgresql.auth.username }}
{{- $database := .Values.postgresql.auth.database }}
{{- $databaseUrl := printf "postgresql://%s:%s@%s:%s/%s" $username $postgresqlPassword $host $port $database }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "postgresql.auth.existingSecret is required" .Values.postgresql.auth.existingSecret }}
  labels:
    {{- include "rails.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ $databaseUrl | b64enc }}
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ $postgresqlPasswordB64 }}
  {{ .Values.postgresql.auth.secretKeys.adminPasswordKey }}: {{ $postgresqlAdminPasswordB64 }}
{{- end }}
---
{{- if .Values.redis.enabled }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (required "redis.auth.existingSecret is required" .Values.redis.auth.existingSecret)).data | default dict }}
{{- $redisPasswordB64 := (index $secret "redis-password") | default (randAlphaNum 16 | b64enc) }}
{{- $redisPassword := $redisPasswordB64 | b64dec }}
{{- $host := printf "%s-master.%s.svc.cluster.local" (printf "%s-%s" .Release.Name "redis") .Release.Namespace }}
{{- $port := "6379" }}
{{- $redisUrl := printf "redis://:%s@%s:%s/0" $redisPassword $host $port }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "redis.auth.existingSecret is required" .Values.redis.auth.existingSecret }}
  labels:
    {{- include "rails.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_URL: {{ $redisUrl | b64enc }}
  redis-password: {{ $redisPasswordB64 }}
{{- end }}
