apiVersion: v2
name: catalyst
description: A Helm chart that includes ingress-nginx, cert-manager, CloudNativePG, and Istio service mesh for the Catalyst platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ingress-nginx
    version: 4.11.3
    repository: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    version: v1.18.2
    repository: oci://quay.io/jetstack/charts
  - name: cloudnative-pg
    version: 0.23.0
    repository: https://cloudnative-pg.github.io/charts
  - name: base
    alias: istio-base
    version: 1.24.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.24.2
    repository: https://istio-release.storage.googleapis.com/charts
